import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';

import { httpStatusCodeMap } from './net/httpStatusCodeMap';
import { daysInSeconds } from './utils/time';

const { OK } = httpStatusCodeMap;

/**
 * Max cache live time in `days` for fonts.
 * @type {Number}
 */
const fontsMaxAge = 365;

/**
 * Max cache live time in `days` for images.
 * @type {Number}
 */
const imagesMaxAge = 30;

clientsClaim();

/**
 * We are not wrapping it in a 'message' event as per the new update.
 * @see https://developers.google.com/web/tools/workbox/modules/workbox-core
 */
self.skipWaiting();

/**
 * Precache all the assets generated by your build process.
 * Their URLs are injected into the manifest variable below.
 * This variable must be present somewhere in your service worker file,
 * even if you decide not to use precaching. See https://cra.link/PWA
 */
precacheAndRoute(self.__WB_MANIFEST);

/**
 * Cache the Google Fonts stylesheets with a stale-while-revalidate strategy.
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
 */
registerRoute(
    ({ url }) => url.origin === 'https://fonts.googleapis.com',
    new StaleWhileRevalidate({
        cacheName: 'google-fonts-stylesheets',
    })
);

/**
 * Cache the underlying font files with a cache-first strategy for 1 year.
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#google_fonts
 */
registerRoute(
    ({ url }) => url.origin === 'https://fonts.gstatic.com',
    new CacheFirst({
        cacheName: 'google-fonts-webfonts',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, OK],
            }),
            new ExpirationPlugin({
                maxEntries: 30,
                maxAgeSeconds: daysInSeconds(fontsMaxAge),
            }),
        ],
    })
);

/**
 * We use CacheFirst for images because, images are not going to change very often,
 * so it does not make sense to revalidate images on every request.
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#caching_images
 */
registerRoute(
    ({ request }) => request.destination === 'image',
    new CacheFirst({
        cacheName: 'images',
        plugins: [
            new CacheableResponsePlugin({
                statuses: [0, OK],
            }),
            new ExpirationPlugin({
                maxEntries: 60,
                maxAgeSeconds: daysInSeconds(imagesMaxAge),
            }),
        ],
    })
);

/**
 * @see https://developers.google.com/web/tools/workbox/guides/common-recipes#cache_css_and_javascript_files
 */
registerRoute(
    ({ request }) => request.destination === 'script' ||
        request.destination === 'style',
    new StaleWhileRevalidate({
        cacheName: 'static-resources',
    })
);

